"""Generate the import/export codec for one Memory Schema.

The codec is the ONLY sanctioned crossing between the historical flat image
and detached native values:

    import_region(mem)    -> a plain dict of detached field values
    export_region(mem, v) -> writes the fields back over the historical bytes

Generated, never handwritten. Specialized per schema -- no runtime
reflection -- and every generated module
embeds the schema digest plus the input digest, so a codec from a stale
schema generation REFUSES at import time rather than quietly transcoding
with an outdated layout (§11.6).

THE CODEC LAW (§11.1) is the gate this enables: import then export must
preserve every owned or preserved historical byte -- including padding
between fields, which the export must copy through untouched, NOT
re-synthesize.  The generated law test round-trips a seeded image and
requires byte equality over the full extent.

The anti-pattern this must never regress into (§1): a dataclass whose
field_06 secretly performs memory.read_u16(base+6) is not memoryless -- the
import produces DETACHED values and the historical image is not consulted
again until export.

What this generator does NOT generate, refused loudly instead:
  * ALIAS_VIEW regions -- they never export independently (§10); the codec
    belongs to the canonical owner alone;
  * ELIMINATED regions -- there is nothing to transcode;
  * fields whose signedness is unproven (native_signed=None) when a signed
    native value is requested -- the codec imports the RAW unsigned bits and
    the schema records that the meaning is undecided.
"""
from __future__ import annotations

from .memory_schema import Comparison, Ownership, Region, Schema


class CodecRefusal(Exception):
    """A region this generator will not produce a codec for, by design."""


def _rd(width: int, seg: str, off_expr: str) -> str:
    if width == 1:
        return f"mem.rb({seg}, {off_expr})"
    if width == 2:
        return f"mem.rw({seg}, {off_expr})"
    raise CodecRefusal(f"unsupported field width {width} (1 and 2 byte "
                       f"fields this generator; wider needs another capability)")


def _wr(width: int, seg: str, off_expr: str, val: str) -> str:
    return (f"mem.wb({seg}, {off_expr}, {val})" if width == 1
            else f"mem.ww({seg}, {off_expr}, {val})")


def emit_codec(region: Region, schema: Schema, *, seg_expr: str) -> str:
    """The codec module source for ONE region.

    ``seg_expr``: the Python expression for the segment VALUE at runtime
    (e.g. a boot-header constant or a snapshot register) -- supplied by the
    port, because dos_re does not know any game's segment values.
    """
    if region.ownership is Ownership.ALIAS_VIEW:
        raise CodecRefusal(
            f"{region.name}: an ALIAS_VIEW never exports independently; "
            f"generate the codec for {region.canonical_owner!r}")
    if region.ownership is Ownership.ELIMINATED:
        raise CodecRefusal(f"{region.name}: ELIMINATED has nothing to "
                           f"transcode")
    if not region.fields and region.ownership is Ownership.NATIVE:
        raise CodecRefusal(
            f"{region.name}: NATIVE with no declared fields would detach "
            f"an opaque blob; declare fields or use HISTORICAL_OPAQUE")

    covered = set()
    for f in region.fields:
        covered.update(range(f.offset, f.offset + f.width))
    padding = [o for o in range(region.extent) if o not in covered]

    L = []
    A = L.append
    A('"""AUTOGENERATED by dos_re.lift.emit_codec -- the import/export')
    A(f'codec for region {region.name!r}. DO NOT hand-edit; regenerate.')
    A('')
    A('The ONLY sanctioned crossing between the historical flat image and')
    A('detached native values.  Import produces PLAIN VALUES: nothing here')
    A('retains the mem handle, so a consumer cannot secretly re-read the')
    A('flat image through this object (the field_06-in-a-costume')
    A('anti-pattern).  Padding bytes are copied through verbatim on export,')
    A('never re-synthesized.')
    A('"""')
    A('')
    A(f'SCHEMA_DIGEST = "{schema.digest()}"')
    A(f'INPUT_DIGEST = "{schema.input_digest}"')
    A(f'REGION = "{region.name}"')
    A(f'BASE = {region.base:#06x}')
    A(f'EXTENT = {region.extent}')
    A('')
    A('')
    A('def check_generation(expected_schema_digest):')
    A('    """Refuse a stale codec BEFORE it transcodes anything (section 11.6).')
    A('    A codec generated from an outdated schema would read the wrong')
    A('    offsets and widths -- silently, because bytes have no schema."""')
    A('    if expected_schema_digest != SCHEMA_DIGEST:')
    A('        raise RuntimeError(')
    A(f'            "codec for {region.name!r} was generated from schema "')
    A('            f"{SCHEMA_DIGEST}, caller expects "')
    A('            f"{expected_schema_digest}: STALE GENERATION, regenerate"')
    A('        )')
    A('')
    A('')
    A(f'def import_region(mem, {seg_expr}):')
    A('    """Historical bytes -> detached plain values."""')
    A('    return {')
    for f in region.fields:
        expr = _rd(f.width, seg_expr, f"BASE + {f.offset:#x}")
        if f.native_signed and f.width == 2:
            expr = f"(lambda v: v - 0x10000 if v >= 0x8000 else v)({expr})"
        elif f.native_signed and f.width == 1:
            expr = f"(lambda v: v - 0x100 if v >= 0x80 else v)({expr})"
        A(f'        "{f.name}": {expr},')
    if padding:
        A(f'        # padding preserved for the codec law: {len(padding)} '
          f'byte(s) not covered by any field')
        A(f'        "_pad": tuple(mem.rb({seg_expr}, BASE + o) '
          f'for o in {tuple(padding)!r}),')
    A('    }')
    A('')
    A('')
    A(f'def export_region(mem, values, {seg_expr}):')
    A('    """Detached values -> historical bytes.  Padding is written back')
    A('    from the imported copy, so import-then-export is byte-identical')
    A('    over the whole extent (the codec law, section 11.1)."""')
    for f in region.fields:
        val = f'values["{f.name}"]'
        if f.native_signed:
            mask = 0xFFFF if f.width == 2 else 0xFF
            val = f"({val}) & {mask:#x}"
        elif f.width == 2:
            val = f"({val}) & 0xFFFF"
        else:
            val = f"({val}) & 0xFF"
        A(f'    {_wr(f.width, seg_expr, f"BASE + {f.offset:#x}", val)}')
    if padding:
        A(f'    for o, b in zip({tuple(padding)!r}, values["_pad"]):')
        A(f'        mem.wb({seg_expr}, BASE + o, b)')
    A('')
    return "\n".join(L)


def emit_codec_law_test(region: Region, schema: Schema, *,
                        seg_expr: str, module: str) -> str:
    """The GENERATED law test for one region (§11.1): import then export
    preserves every byte of the extent, on memory this test seeds itself.

    Generated alongside the codec so the pair cannot drift: a codec without
    its law test is exactly the kind of unchecked artifact class where the
    next defect goes.
    """
    L = []
    A = L.append
    A('"""AUTOGENERATED codec-law test. DO NOT hand-edit."""')
    A(f'from {module} import (BASE, EXTENT, SCHEMA_DIGEST,')
    A(f'                      export_region, import_region)')
    A('')
    A('')
    A('class _Mem:')
    A('    """Seeded fake guest memory, deliberately varied bytes."""')
    A('')
    A('    def __init__(self, seed=1):')
    A('        self.b = {}')
    A('        self.seed = seed')
    A('')
    A('    def _addr(self, seg, off):')
    A('        return ((seg << 4) + off) & 0xFFFFF')
    A('')
    A('    def rb(self, seg, off):')
    A('        a = self._addr(seg, off)')
    A('        if a not in self.b:')
    A('            self.b[a] = (a * 2654435761 ^ self.seed * 40503) >> 13 & 0xFF')
    A('        return self.b[a]')
    A('')
    A('    def rw(self, seg, off):')
    A('        return self.rb(seg, off) | (self.rb(seg, off + 1) << 8)')
    A('')
    A('    def wb(self, seg, off, v):')
    A('        self.b[self._addr(seg, off)] = v & 0xFF')
    A('')
    A('    def ww(self, seg, off, v):')
    A('        self.wb(seg, off, v)')
    A('        self.wb(seg, off + 1, v >> 8)')
    A('')
    A('')
    A('def test_codec_law_import_then_export_is_byte_identical():')
    A('    """section 11.1: every owned/preserved byte -- fields AND padding --')
    A('    survives the round trip exactly."""')
    A('    seg = 0x1000')
    A('    mem = _Mem()')
    A('    before = [mem.rb(seg, BASE + o) for o in range(EXTENT)]')
    A(f'    values = import_region(mem, {seg_expr}=seg)')
    A(f'    export_region(mem, values, {seg_expr}=seg)')
    A('    after = [mem.rb(seg, BASE + o) for o in range(EXTENT)]')
    A('    assert after == before, [')
    A('        (i, a, b) for i, (a, b) in enumerate(zip(before, after))')
    A('        if a != b]')
    A('')
    A('')
    A('def test_imported_values_are_detached():')
    A('    """Mutating the image after import must not change the values --')
    A('    the anti-pattern gate: a view object would fail this."""')
    A('    seg = 0x1000')
    A('    mem = _Mem()')
    A(f'    values = import_region(mem, {seg_expr}=seg)')
    A('    snapshot = dict(values)')
    A('    for o in range(EXTENT):')
    A('        mem.wb(seg, BASE + o, 0xEE)')
    A('    assert values == snapshot, "imported values still read the image"')
    A('')
    return "\n".join(L)


def emit_native_state(region: Region, schema: Schema, *,
                      codec_module: str) -> str:
    """The detached native-state module for one selected region.

    This object IS the authority once attached: promoted core sites read and
    write it, the historical byte is poisoned, and export regenerates the
    historical bytes only for boundary comparison.  Its guards are the
    RUNTIME wall: unattached access, segment mismatch, or an offset outside
    the declared fields all raise -- never a silent fall-through to the
    image.

    Modes (section 12): attach_import is IMPORT_EXPORT (authority transfers
    from the image ONCE); attach_blank is the region-level DETACHED-ARTIFACT
    gate -- native state starts from schema defaults and the image never
    supplies the value, which is only sound where every read is dominated by
    a native write (the oracle differential falsifies it otherwise).
    """
    if region.ownership is not Ownership.NATIVE:
        raise CodecRefusal(f"{region.name}: native state is only generated "
                           f"for NATIVE ownership")
    off2field = {}
    for f in region.fields:
        if f.width != 1:
            raise CodecRefusal("native-state accessor: width-1 fields this "
                               "generator; wider needs another capability")
        off2field[region.base + f.offset] = f.name
    L = []
    A = L.append
    A('"""AUTOGENERATED by dos_re.lift.emit_codec -- detached native state')
    A(f'for region {region.name!r}. DO NOT hand-edit; regenerate.')
    A('')
    A('Once attached, THIS is the authority for the region.  The historical')
    A('byte range is poisoned; export regenerates it only for boundary')
    A('comparison.  Every guard raises rather than falling through to the')
    A('image -- two writable authorities would violate ownership')
    A('prevent (section 12: no mode permits two writable authorities)."""')
    A(f'from {codec_module} import export_region, import_region')
    A('')
    A(f'SCHEMA_DIGEST = "{schema.digest()}"')
    A(f'REGION = "{region.name}"')
    A(f'BASE = {region.base:#06x}')
    A(f'EXTENT = {region.extent}')
    A(f'_OFF2FIELD = {off2field!r}')
    A('POISON = 0xA5')
    A('')
    A('')
    A('class _NativeState:')
    A('    def __init__(self):')
    A('        self.values = None        # detached plain values, or None')
    A('        self.seg = None           # the segment value bound at attach')
    A('        self._lazy_mem = None     # armed by begin_lazy_import')
    A('        self._lazy_blank = False')
    A('')
    A('    # -- lazy attach: the OWNING SITE binds the segment ------------')
    A('    # The boot snapshot ds is not necessarily the segment the owner')
    A('    # runs with (measured: boot ds=0x1000 vs the game data segment),')
    A('    # so guessing at boot poisons the wrong byte and the mismatch')
    A('    # guard kills the run.  Instead the FIRST promoted-site access')
    A('    # binds the segment it was actually called with; before that')
    A('    # touch the image byte is still authoritative and untouched, so')
    A('    # nothing is lost -- first-touch perturbation evidence covers it.')
    A('    def begin_lazy_import(self, mem):')
    A('        if self.values is not None:')
    A('            raise RuntimeError(f"{REGION}: already attached")')
    A('        self._lazy_mem = mem')
    A('')
    A('    def begin_lazy_blank(self):')
    A('        if self.values is not None:')
    A('            raise RuntimeError(f"{REGION}: already attached")')
    A('        self._lazy_blank = True')
    A('')
    A('    def _lazy_attach(self, seg):')
    A('        if self._lazy_blank:')
    A('            self.attach_blank(seg)')
    A('        elif self._lazy_mem is not None:')
    A('            mem, self._lazy_mem = self._lazy_mem, None')
    A('            self.attach_import(mem, seg)')
    A('        else:')
    A('            raise RuntimeError(f"{REGION}: access while detached and '
      'no lazy mode armed -- the promoted core ran without a bridge")')
    A('')
    A('    # -- lifecycle -------------------------------------------------')
    A('    def attach_import(self, mem, seg):')
    A('        """IMPORT_EXPORT: authority transfers from the image ONCE."""')
    A('        if self.values is not None:')
    A('            raise RuntimeError(f"{REGION}: already attached -- '
      're-import inside a run is a proof failure, not synchronization")')
    A('        self.values = import_region(mem, seg)')
    A('        self.seg = seg')
    A('        self.poison(mem)')
    A('')
    A('    def attach_blank(self, seg):')
    A('        """DETACHED-ARTIFACT gate: the image never supplies the value.')
    A('        Sound only where a native write dominates every read; the')
    A('        oracle differential falsifies this mode if not."""')
    A('        if self.values is not None:')
    A('            raise RuntimeError(f"{REGION}: already attached")')
    A('        self.values = {name: 0 for name in _OFF2FIELD.values()}')
    A('        self.seg = seg')
    A('')
    A('    def poison(self, mem):')
    A('        for o in range(EXTENT):')
    A('            mem.wb(self.seg, BASE + o, POISON)')
    A('')
    A('    def export(self, mem):')
    A('        """Regenerate historical bytes for boundary comparison."""')
    A('        if self.values is None:')
    A('            raise RuntimeError(f"{REGION}: export while detached")')
    A('        export_region(mem, self.values, self.seg)')
    A('')
    A('    def detach(self):')
    A('        """Drop ALL bridge authority -- values, segment, AND any armed')
    A('        lazy mode.  Clearing only the values left begin_lazy_blank/')
    A('        begin_lazy_import armed, so the next access silently re-attached')
    A('        (to whatever segment happened to arrive) instead of refusing."""')
    A('        self.values = None')
    A('        self.seg = None')
    A('        self._lazy_mem = None')
    A('        self._lazy_blank = False')
    A('')
    A('    # -- the promoted-site accessor (mem-shaped ON PURPOSE: the')
    A('    # translated instruction stays byte-identical in cost and flags;')
    A('    # later semantic naming does not alter proven ownership) --------')
    A('    def rb(self, seg, off):')
    A('        if self.values is None:')
    A('            self._lazy_attach(seg)')
    A('        if seg != self.seg:')
    A('            raise RuntimeError(f"{REGION}: segment {seg:#x} does not '
      'match the attached segment {self.seg:#x} -- the ownership premise '
      'is violated, refusing")')
    A('        name = _OFF2FIELD.get(off)')
    A('        if name is None:')
    A('            raise RuntimeError(f"{REGION}: offset {off:#x} is not a '
      'declared field")')
    A('        return self.values[name]')
    A('')
    A('    def wb(self, seg, off, v):')
    A('        if self.values is None:')
    A('            self._lazy_attach(seg)')
    A('        if seg != self.seg:')
    A('            raise RuntimeError(f"{REGION}: segment mismatch on write")')
    A('        name = _OFF2FIELD.get(off)')
    A('        if name is None:')
    A('            raise RuntimeError(f"{REGION}: offset {off:#x} is not a '
      'declared field")')
    A('        self.values[name] = v & 0xFF')
    A('')
    A('')
    A('NATIVE = _NativeState()')
    A('')
    return "\n".join(L)
