"""The ABI-recovered emitter (M3b, slice 1) -- public contract entry +
contract-proof shadow over the ONE mechanical core.

Consumes an ABI-contract proposal (dos_re.lift.contracts census output --
itself pure recovery-IR analysis) and generates, per function, a module
with TWO entrypoints around the single generated algorithmic core (the
mechanical CPUless recovered function -- no duplicate implementation):

* the PUBLIC ABI-recovered entry (``abi_CCCC_IIII``, or the recovered name
  when the naming table supplies one): semantic register parameters only;
  ``cs`` is bound statically (the function's own segment); the machine
  stack, where the core still uses it, is ONE explicitly-typed ``stack``
  parameter -- an (ss, sp) pair, classified HISTORICAL MEMORY VIEW, that
  disappears when the core re-emission (slice 2) turns local push/pop into
  Python locals.  Returns the caller-observed registers as a normal Python
  value (scalar / tuple / None) -- never the full written-register dict.

* the CONTRACT-PROOF SHADOW (``func_CCCC_IIII``, the mechanical name):
  preserves the exact mechanical ABI but XOR-PERTURBS every register output
  the census proved unobserved.  Substituting the shadow module for the
  mechanical one (sys.modules pre-registration) and replaying the canonical
  demo through the acceptance gate proves the narrowed contract END TO END:
  if anything -- a caller, a boundary register digest -- actually observes
  a "dropped" output, the perturbation surfaces and the oracle comparison
  fails loudly at that boundary.  XOR (not a constant) guarantees the value
  differs from the mechanical one whenever it is looked at.

Refusal-first: a proposal with refusals, or a shape this slice does not
support, raises -- never a silently degraded module.
"""
from __future__ import annotations

from .emit_cpuless import Refusal

#: XOR perturbation for proven-unobserved outputs: guaranteed to differ
#: from the mechanical value if anything observes it.
POISON_XOR = 0xA5A5


def _stem(key: str) -> str:
    cs, ip = key.split(":")
    return f"{int(cs, 16):04x}_{int(ip, 16):04x}"


def emit_abi_module(key: str, proposal: dict, *, import_base: str,
                    name: str | None = None) -> str:
    """Generate the ABI-recovered module source for one census proposal.

    ``import_base``: the package holding the mechanical recovered modules
    (e.g. ``lemmings.recovered``).  ``name``: optional recovered name for
    the public entry (provenance stays the address)."""
    if proposal.get("refusals"):
        raise Refusal("contract-not-promotable: "
                      + ",".join(r["reason"] for r in proposal["refusals"]))
    stem = _stem(key)
    cs = int(key.split(":")[0], 16)
    mech = f"func_{stem}"
    public = name or f"abi_{stem}"
    if not public.isidentifier():
        raise Refusal(f"recovered-name-not-identifier: {public!r}")

    params = [p["reg"] for p in proposal["params"]]
    returns = list(proposal["returns"])
    dropped = list(proposal["dropped_outputs"])
    machine = set(proposal["machine_private"])
    unknown_machine = machine - {"sp", "ss", "cs", "bp"}
    if unknown_machine:
        raise Refusal("unsupported-machine-private: "
                      + ",".join(sorted(unknown_machine)))
    if "bp" in machine:
        # framed stack args (slice 2 material: no framed functions in a
        # register-convention corpus; refuse rather than mis-emit)
        raise Refusal("stack-args-not-yet-emitted")
    needs_stack = bool(machine & {"sp", "ss"})

    sig = ["mem", "plat=None"]
    body_kwargs = [f"{r}={r}" for r in sorted(params)]
    kw = ["*"] if params or needs_stack else []
    if needs_stack:
        kw.append("stack=(0, 0)")
        body_kwargs += ["ss=stack[0]", "sp=stack[1]"]
    kw += [f"{r}=0" for r in sorted(params)]
    if "cs" in machine:
        body_kwargs.append(f"cs=0x{cs:04X}")
    sig_line = ", ".join(sig + kw)
    call_kw = ", ".join(["**_compat"] + body_kwargs)

    if not returns:
        ret_doc, ret_line = "None", "    return None"
    elif len(returns) == 1:
        ret_doc = returns[0]
        ret_line = f"    return _o['{returns[0]}']"
    else:
        ret_doc = "(" + ", ".join(returns) + ")"
        ret_line = ("    return ("
                    + ", ".join(f"_o['{r}']" for r in returns) + ")")

    prov = f"{name} [{key}]" if name else f"[{key}]"
    stack_doc = ("\n    ``stack``: the (ss, sp) machine-stack view "
                 "(historical memory view; slice-2 removes it)."
                 if needs_stack else "")
    lines = [
        '"""AUTOGENERATED by dos_re.lift.emit_abi -- ABI-recovered contract',
        f'for {key} (M3b slice 1: dual entrypoints over the ONE mechanical',
        'core).  DO NOT hand-edit; regenerate.',
        '',
        f'Public contract: {public}({sig_line}) -> {ret_doc}',
        f'Shadow {mech} preserves the mechanical ABI and XOR-perturbs the',
        f'proven-unobserved outputs {tuple(dropped)!r} -- the end-to-end',
        'contract proof when substituted into the acceptance demo.',
        '"""',
        '',
        f'from {import_base}.{mech} import {mech} as _core',
        '',
        f'_DROPPED = {tuple(dropped)!r}',
        f'_POISON_XOR = 0x{POISON_XOR:04X}',
        '',
        '',
        f'def {public}({sig_line}, **_compat):',
        f'    """Public ABI-recovered entry {prov}: semantic contract only.',
        f'    Returns {ret_doc}.{stack_doc}',
        '    ``_compat``: private verification channel (flags word, virtual',
        '    time base) -- not part of the recovered API."""',
        '    _args = (mem,) if plat is None else (mem, plat)',
        f'    _o, _c = _core(*_args, {call_kw})',
        ret_line,
        '',
        '',
        f'def {mech}(mem, *args, **kw):',
        '    """Contract-proof shadow: exact mechanical ABI; the census-',
        '    dropped outputs are XOR-perturbed so any observation anywhere',
        '    diverges the oracle comparison loudly."""',
        '    _o, _c = _core(mem, *args, **kw)',
        '    _o = dict(_o)',
        '    for _r in _DROPPED:',
        '        _o[_r] = (_o[_r] ^ _POISON_XOR) & 0xFFFF',
        '    return _o, _c',
        '',
    ]
    return "\n".join(lines)


def emit_shadow_loader(keys: list[str], *, abi_base: str,
                       import_base: str) -> str:
    """The generated loader that substitutes the contract-proof shadows for
    their mechanical modules.

    Two seams, both required:

    * ``sys.modules`` aliasing (the native-override loader's seam) routes
      every LATER import -- unimported callers, and the dispatch registry's
      lazy ``importlib`` resolution -- through the shadow;
    * RETRO-PATCHING covers the imports that already happened: mechanical
      modules bind their callees at module level (``from ...func_X import
      func_X``), and importing one shadow transitively imports mechanical
      callers of OTHER shadowed functions before those shadows register.
      Every already-materialised namespace -- modules still in sys.modules
      under the recovered package, plus each shadowed core's own module
      globals (reached via ``_core.__globals__``; the module object leaves
      sys.modules when aliased but its function bodies still execute
      against it) -- gets its stale bindings rebound to the shadow.

    A shadowed core's binding of its OWN name is deliberately left alone: a
    self-recursive core calling its own shadow would XOR-perturb twice and
    cancel the poison (the self-edge composes conservatively anyway)."""
    stems = ", ".join(f'"{_stem(k)}"' for k in sorted(keys))
    return "\n".join([
        '"""AUTOGENERATED by dos_re.lift.emit_abi -- contract-proof shadow',
        'loader (M3b).  DO NOT hand-edit; regenerate."""',
        '',
        'import importlib',
        'import sys',
        '',
        f'STEMS = ({stems},)',
        '',
        '',
        'def install_shadows(stems=STEMS):',
        '    """Substitute every contract-proof shadow for its mechanical',
        '    module: sys.modules alias for future imports + retro-patch of',
        '    every already-materialised binding.  Idempotent."""',
        '    shadows = {}',
        '    for s in stems:',
        f'        shadows[s] = importlib.import_module("{abi_base}.abi_" + s)',
        '    for s, mod in shadows.items():',
        f'        sys.modules["{import_base}.func_" + s] = mod',
        '    # namespaces holding stale mechanical bindings: recovered-package',
        '    # modules still in sys.modules + each shadowed core\'s globals',
        '    spaces = []',
        '    for name, m in list(sys.modules.items()):',
        f'        if m is not None and name.startswith("{import_base}."):',
        '            spaces.append((None, m.__dict__))',
        '    for s, mod in shadows.items():',
        '        spaces.append((s, getattr(mod, "_core").__globals__))',
        '    patched = 0',
        '    for owner, ns in spaces:',
        '        for s, mod in shadows.items():',
        '            if s == owner:',
        '                continue          # keep the self-edge unshadowed',
        '            f = "func_" + s',
        '            repl = getattr(mod, f)',
        '            if f in ns and ns[f] is not repl:',
        '                ns[f] = repl',
        '                patched += 1',
        '    return len(shadows), patched',
        '',
    ])
