"""Generate the import/export codec for one Memory Schema (M4 §14.4).

The codec is the ONLY sanctioned crossing between the historical flat image
and detached native values:

    import_region(mem)    -> a plain dict of detached field values
    export_region(mem, v) -> writes the fields back over the historical bytes

Generated, never handwritten (§1.4).  Specialized per schema -- no runtime
reflection, mirroring the pipeline's habit -- and every generated module
embeds the schema digest plus the input digest, so a codec from a stale
schema generation REFUSES at import time rather than quietly transcoding
with an outdated layout (§11.6).

THE CODEC LAW (§11.1) is the gate this enables: import then export must
preserve every owned or preserved historical byte -- including padding
between fields, which the export must copy through untouched, NOT
re-synthesize.  The generated law test round-trips a seeded image and
requires byte equality over the full extent.

The anti-pattern this must never regress into (§1): a dataclass whose
field_06 secretly performs memory.read_u16(base+6) is not memoryless -- the
import produces DETACHED values and the historical image is not consulted
again until export.

What this slice does NOT generate, refused loudly instead:
  * ALIAS_VIEW regions -- they never export independently (§10); the codec
    belongs to the canonical owner alone;
  * ELIMINATED regions -- there is nothing to transcode;
  * fields whose signedness is unproven (native_signed=None) when a signed
    native value is requested -- the codec imports the RAW unsigned bits and
    the schema records that the meaning is undecided.
"""
from __future__ import annotations

from .memory_schema import Comparison, Ownership, Region, Schema


class CodecRefusal(Exception):
    """A region this generator will not produce a codec for, by design."""


def _rd(width: int, seg: str, off_expr: str) -> str:
    if width == 1:
        return f"mem.rb({seg}, {off_expr})"
    if width == 2:
        return f"mem.rw({seg}, {off_expr})"
    raise CodecRefusal(f"unsupported field width {width} (1 and 2 byte "
                       f"fields this slice; wider is a later capability)")


def _wr(width: int, seg: str, off_expr: str, val: str) -> str:
    return (f"mem.wb({seg}, {off_expr}, {val})" if width == 1
            else f"mem.ww({seg}, {off_expr}, {val})")


def emit_codec(region: Region, schema: Schema, *, seg_expr: str) -> str:
    """The codec module source for ONE region.

    ``seg_expr``: the Python expression for the segment VALUE at runtime
    (e.g. a boot-header constant or a snapshot register) -- supplied by the
    port, because dos_re does not know any game's segment values.
    """
    if region.ownership is Ownership.ALIAS_VIEW:
        raise CodecRefusal(
            f"{region.name}: an ALIAS_VIEW never exports independently; "
            f"generate the codec for {region.canonical_owner!r}")
    if region.ownership is Ownership.ELIMINATED:
        raise CodecRefusal(f"{region.name}: ELIMINATED has nothing to "
                           f"transcode")
    if not region.fields and region.ownership is Ownership.NATIVE:
        raise CodecRefusal(
            f"{region.name}: NATIVE with no declared fields would detach "
            f"an opaque blob; declare fields or use HISTORICAL_OPAQUE")

    covered = set()
    for f in region.fields:
        covered.update(range(f.offset, f.offset + f.width))
    padding = [o for o in range(region.extent) if o not in covered]

    L = []
    A = L.append
    A('"""AUTOGENERATED by dos_re.lift.emit_codec -- the import/export')
    A(f'codec for region {region.name!r} (M4).  DO NOT hand-edit; regenerate.')
    A('')
    A('The ONLY sanctioned crossing between the historical flat image and')
    A('detached native values.  Import produces PLAIN VALUES: nothing here')
    A('retains the mem handle, so a consumer cannot secretly re-read the')
    A('flat image through this object (the field_06-in-a-costume')
    A('anti-pattern).  Padding bytes are copied through verbatim on export,')
    A('never re-synthesized.')
    A('"""')
    A('')
    A(f'SCHEMA_DIGEST = "{schema.digest()}"')
    A(f'INPUT_DIGEST = "{schema.input_digest}"')
    A(f'REGION = "{region.name}"')
    A(f'BASE = {region.base:#06x}')
    A(f'EXTENT = {region.extent}')
    A('')
    A('')
    A('def check_generation(expected_schema_digest):')
    A('    """Refuse a stale codec BEFORE it transcodes anything (section 11.6).')
    A('    A codec generated from an outdated schema would read the wrong')
    A('    offsets and widths -- silently, because bytes have no schema."""')
    A('    if expected_schema_digest != SCHEMA_DIGEST:')
    A('        raise RuntimeError(')
    A(f'            "codec for {region.name!r} was generated from schema "')
    A('            f"{SCHEMA_DIGEST}, caller expects "')
    A('            f"{expected_schema_digest}: STALE GENERATION, regenerate"')
    A('        )')
    A('')
    A('')
    A(f'def import_region(mem, {seg_expr}):')
    A('    """Historical bytes -> detached plain values."""')
    A('    return {')
    for f in region.fields:
        expr = _rd(f.width, seg_expr, f"BASE + {f.offset:#x}")
        if f.native_signed and f.width == 2:
            expr = f"(lambda v: v - 0x10000 if v >= 0x8000 else v)({expr})"
        elif f.native_signed and f.width == 1:
            expr = f"(lambda v: v - 0x100 if v >= 0x80 else v)({expr})"
        A(f'        "{f.name}": {expr},')
    if padding:
        A(f'        # padding preserved for the codec law: {len(padding)} '
          f'byte(s) not covered by any field')
        A(f'        "_pad": tuple(mem.rb({seg_expr}, BASE + o) '
          f'for o in {tuple(padding)!r}),')
    A('    }')
    A('')
    A('')
    A(f'def export_region(mem, values, {seg_expr}):')
    A('    """Detached values -> historical bytes.  Padding is written back')
    A('    from the imported copy, so import-then-export is byte-identical')
    A('    over the whole extent (the codec law, section 11.1)."""')
    for f in region.fields:
        val = f'values["{f.name}"]'
        if f.native_signed:
            mask = 0xFFFF if f.width == 2 else 0xFF
            val = f"({val}) & {mask:#x}"
        elif f.width == 2:
            val = f"({val}) & 0xFFFF"
        else:
            val = f"({val}) & 0xFF"
        A(f'    {_wr(f.width, seg_expr, f"BASE + {f.offset:#x}", val)}')
    if padding:
        A(f'    for o, b in zip({tuple(padding)!r}, values["_pad"]):')
        A(f'        mem.wb({seg_expr}, BASE + o, b)')
    A('')
    return "\n".join(L)


def emit_codec_law_test(region: Region, schema: Schema, *,
                        seg_expr: str, module: str) -> str:
    """The GENERATED law test for one region (§11.1): import then export
    preserves every byte of the extent, on memory this test seeds itself.

    Generated alongside the codec so the pair cannot drift: a codec without
    its law test is exactly the kind of unchecked artifact class where the
    next defect goes.
    """
    L = []
    A = L.append
    A('"""AUTOGENERATED codec-law test (M4 section 11.1).  DO NOT hand-edit."""')
    A(f'from {module} import (BASE, EXTENT, SCHEMA_DIGEST,')
    A(f'                      export_region, import_region)')
    A('')
    A('')
    A('class _Mem:')
    A('    """Seeded fake guest memory, deliberately varied bytes."""')
    A('')
    A('    def __init__(self, seed=1):')
    A('        self.b = {}')
    A('        self.seed = seed')
    A('')
    A('    def _addr(self, seg, off):')
    A('        return ((seg << 4) + off) & 0xFFFFF')
    A('')
    A('    def rb(self, seg, off):')
    A('        a = self._addr(seg, off)')
    A('        if a not in self.b:')
    A('            self.b[a] = (a * 2654435761 ^ self.seed * 40503) >> 13 & 0xFF')
    A('        return self.b[a]')
    A('')
    A('    def rw(self, seg, off):')
    A('        return self.rb(seg, off) | (self.rb(seg, off + 1) << 8)')
    A('')
    A('    def wb(self, seg, off, v):')
    A('        self.b[self._addr(seg, off)] = v & 0xFF')
    A('')
    A('    def ww(self, seg, off, v):')
    A('        self.wb(seg, off, v)')
    A('        self.wb(seg, off + 1, v >> 8)')
    A('')
    A('')
    A('def test_codec_law_import_then_export_is_byte_identical():')
    A('    """section 11.1: every owned/preserved byte -- fields AND padding --')
    A('    survives the round trip exactly."""')
    A('    seg = 0x1000')
    A('    mem = _Mem()')
    A('    before = [mem.rb(seg, BASE + o) for o in range(EXTENT)]')
    A(f'    values = import_region(mem, {seg_expr}=seg)')
    A(f'    export_region(mem, values, {seg_expr}=seg)')
    A('    after = [mem.rb(seg, BASE + o) for o in range(EXTENT)]')
    A('    assert after == before, [')
    A('        (i, a, b) for i, (a, b) in enumerate(zip(before, after))')
    A('        if a != b]')
    A('')
    A('')
    A('def test_imported_values_are_detached():')
    A('    """Mutating the image after import must not change the values --')
    A('    the anti-pattern gate: a view object would fail this."""')
    A('    seg = 0x1000')
    A('    mem = _Mem()')
    A(f'    values = import_region(mem, {seg_expr}=seg)')
    A('    snapshot = dict(values)')
    A('    for o in range(EXTENT):')
    A('        mem.wb(seg, BASE + o, 0xEE)')
    A('    assert values == snapshot, "imported values still read the image"')
    A('')
    return "\n".join(L)
