"""Self-describing recovered-island metadata + auto-discovery.

A recovered function carries its own provenance via the :func:`oracle_link`
decorator: which original ASM boundary it replaces, the caller-visible contract
it honours, how far it is verified, and the larger subsystem it will merge
into. The decorator returns the function unchanged, so recovered code keeps
normal signatures and reads like ordinary source — this is a
documentation/testing aid, never a runtime dependency or an ASM dispatcher.

The principle: **code is the source of truth.** Metadata lives next to the
code; docs/registries are *discovered and generated* from it
(:func:`collect_islands`, :func:`render_manifest`) rather than hand-maintained,
so they cannot drift. The generated manifest is the authoritative answer to
"what is recovered?" — the number the whole project is steered by.

A game adapter supplies its own package list and manifest path, regenerates
with ``python tools/gen_island_manifest.py <packages...> -o <manifest.md>``,
and adds a drift test (generated == committed) plus a well-formedness test
(every island has a valid boundary, a non-empty contract, and a merge target).
See the pre2_port originals ``tests/test_island_registry.py`` /
``tests/test_oracle_links.py`` for the proven shape.

Origin: promoted from the Prehistorik 2 port's ``pre2/islands.py`` (an
equivalent registry existed in the Overkill port); package list and manifest
path parameterized, wording generalized.
"""
from __future__ import annotations

import importlib
import pkgutil
from dataclasses import dataclass
from typing import Iterable, Sequence

#: allowed maturity levels, in increasing confidence
#: GUESS        - hypothesised from a reference/heuristic, not yet checked vs ASM
#: OBSERVED     - behaviour watched in the running ASM, not yet reimplemented
#: RECOVERED    - reimplemented as clean source, not yet diffed vs ASM
#: ASM_MATCHED  - output diffed against ASM on captured cases
#: VERIFIED     - byte-exact vs ASM under in-VM lockstep over real runs
#: CANONICAL    - verified and adopted as the source of truth (ASM retired for it)
STATUSES = ("GUESS", "OBSERVED", "RECOVERED", "ASM_MATCHED", "VERIFIED", "CANONICAL")


@dataclass(frozen=True)
class OracleLink:
    boundary: str            # original ASM CS:IP replaced, e.g. "1030:348D"
    contract: str            # caller-visible side effects this function reproduces
    status: str = "RECOVERED"
    merge_target: str = ""   # the larger recovered subsystem this island merges into

    def __post_init__(self) -> None:
        if self.status not in STATUSES:
            raise ValueError(f"OracleLink status {self.status!r} not in {STATUSES}")


def oracle_link(boundary: str, contract: str, status: str = "RECOVERED", merge_target: str = ""):
    """Attach an :class:`OracleLink` to a recovered function (returns it unchanged)."""
    link = OracleLink(boundary, contract, status, merge_target)

    def _decorate(fn):
        fn.oracle_link = link
        return fn

    return _decorate


def collect_islands(packages: Sequence[str]) -> list[tuple[str, str, OracleLink]]:
    """Discover every recovered island by scanning the given packages.

    Walks the package modules, imports them, and yields
    ``(module, qualname, OracleLink)`` for each function carrying ``oracle_link``.
    Adding a new island anywhere under these packages needs no manual registration.
    """
    found: list[tuple[str, str, OracleLink]] = []
    for pkg_name in packages:
        pkg = importlib.import_module(pkg_name)
        modules: Iterable[str] = (
            info.name for info in pkgutil.walk_packages(pkg.__path__, prefix=pkg_name + ".")
        ) if hasattr(pkg, "__path__") else ()
        for mod_name in (pkg_name, *modules):
            mod = importlib.import_module(mod_name)
            for name, obj in vars(mod).items():
                link = getattr(obj, "oracle_link", None)
                # attribute each island to its *defining* module (skip re-exports)
                if (isinstance(link, OracleLink) and callable(obj)
                        and getattr(obj, "__module__", None) == mod_name):
                    found.append((mod_name, name, link))
    return sorted(found, key=lambda t: (t[2].boundary, t[1]))


def render_manifest(packages: Sequence[str]) -> str:
    """Render the recovered-island manifest (markdown) from the in-code metadata."""
    lines = [
        "# Recovered islands — generated manifest",
        "",
        "<!-- GENERATED by `python tools/gen_island_manifest.py`; do not edit by hand.",
        "     Source of truth = the @oracle_link metadata on each recovered function.",
        "     Add a drift test so this file cannot go stale (generated == committed). -->",
        "",
        "Each row is a recovered leaf/controller. `Status` is the oracle-link confidence",
        "ladder (GUESS -> OBSERVED -> RECOVERED -> ASM_MATCHED -> VERIFIED -> CANONICAL);",
        "`Merge target` names the larger subsystem the island will merge into (the",
        "coastline must move upward over time — hooks are scaffolding, not the final",
        "architecture).",
        "",
        "| ASM boundary | Function | Status | Merge target | Contract |",
        "|---|---|---|---|---|",
    ]
    for modname, name, link in collect_islands(packages):
        short = modname.split(".", 1)[1] if "." in modname else modname
        lines.append(f"| `{link.boundary}` | `{short}.{name}` | {link.status} | "
                     f"{link.merge_target or '—'} | {link.contract} |")
    return "\n".join(lines) + "\n"
