"""abi_promote.py -- generate ABI-recovered modules from the M3b contract
census (dos_re.lift.emit_abi, slice 1).

For every contract-promotable census entry with proven-unobserved outputs
(the poison-proof set) -- or every promotable entry with --all -- emit the
dual-entrypoint module (public ABI-recovered entry + contract-proof shadow)
plus the generated shadow loader.  Substituting the shadows into the
recovered graph and replaying the canonical demo through the acceptance
gate proves the narrowed contracts end to end against the oracle.

Usage:
    python dos_re/tools/abi_promote.py \
        --census artifacts/abi/contract_census.json \
        --import-base lemmings.recovered --abi-base lemmings.recovered_abi \
        --out-dir lemmings/recovered_abi [--all] [--apply]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from dos_re.lift import emit_abi  # noqa: E402
from dos_re.lift.emit_cpuless import Refusal  # noqa: E402


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--census", required=True,
                    help="contract_census.json (dos_re.lift.contracts)")
    ap.add_argument("--import-base", required=True,
                    help="package of the mechanical recovered modules")
    ap.add_argument("--abi-base", required=True,
                    help="package the ABI modules are imported as")
    ap.add_argument("--out-dir", required=True)
    ap.add_argument("--all", action="store_true",
                    help="emit every promotable contract (default: only "
                         "those with dropped outputs -- the poison-proof "
                         "set)")
    ap.add_argument("--entries", default="",
                    help="comma-separated CS:IP subset (bisection aid)")
    ap.add_argument("--apply", action="store_true",
                    help="write the generated files (default: dry run)")
    args = ap.parse_args(argv)

    census = json.loads(Path(args.census).read_text(encoding="utf-8"))
    wanted = ([e.strip().upper() for e in args.entries.split(",")
               if e.strip()] or sorted(census["functions"]))
    emitted: dict[str, str] = {}
    skipped: dict[str, str] = {}
    for key in wanted:
        prop = census["functions"][key]
        if prop["refusals"]:
            skipped[key] = "refused: " + ",".join(
                r["reason"] for r in prop["refusals"])
            continue
        if not args.all and not prop["dropped_outputs"]:
            skipped[key] = "no-dropped-outputs"
            continue
        name = None
        for n in prop.get("notes", ()):
            if n.startswith("name: "):
                name = n.split()[1]
        try:
            emitted[key] = emit_abi.emit_abi_module(
                key, prop, import_base=args.import_base, name=name)
        except Refusal as e:
            skipped[key] = str(e)

    print(f"ABI-recovered emission over {len(wanted)} candidates:")
    print(f"  emitted  {len(emitted):4d}")
    from collections import Counter
    for reason, n in Counter(skipped.values()).most_common():
        print(f"  skipped: {reason:<40} {n:4d}")

    if args.apply and emitted:
        out = Path(args.out_dir)
        out.mkdir(parents=True, exist_ok=True)
        for key, src in sorted(emitted.items()):
            (out / f"abi_{emit_abi._stem(key)}.py").write_text(
                src, encoding="utf-8")
        (out / "shadow_loader.py").write_text(
            emit_abi.emit_shadow_loader(sorted(emitted),
                                        abi_base=args.abi_base,
                                        import_base=args.import_base),
            encoding="utf-8")
        (out / "__init__.py").write_text(
            '"""AUTOGENERATED by dos_re tools/abi_promote.py -- '
            'ABI-recovered contract modules (M3b slice 1).  Regenerate, '
            'do not hand-edit."""\n', encoding="utf-8")
        print(f"wrote {len(emitted)} modules + shadow_loader to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
