"""abi_promote.py -- generate ABI-recovered modules from the M3b contract
census (dos_re.lift.emit_abi, slice 1).

For every contract-promotable census entry with proven-unobserved outputs
(the poison-proof set) -- or every promotable entry with --all -- emit the
dual-entrypoint module (public ABI-recovered entry + contract-proof shadow)
plus the generated shadow loader.  Substituting the shadows into the
recovered graph and replaying the canonical demo through the acceptance
gate proves the narrowed contracts end to end against the oracle.

Usage:
    python dos_re/tools/abi_promote.py \
        --census artifacts/abi/contract_census.json \
        --import-base lemmings.recovered --abi-base lemmings.recovered_abi \
        --out-dir lemmings/recovered_abi [--all] [--apply]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from dos_re.lift import emit_abi  # noqa: E402
from dos_re.lift.emit_cpuless import Refusal  # noqa: E402


def _addr_file(spec: str | None) -> frozenset:
    if not spec:
        return frozenset()
    out = set()
    for line in Path(spec.lstrip("@")).read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            cs, ip = line.split(":")
            out.add((int(cs, 16), int(ip, 16)))
    return frozenset(out)


def _emit_cores(args, census, wanted) -> int:
    """Slice 2: emit the de-stacked ABI core for every destackable leaf."""
    from dos_re.lift.contracts import scan_for

    if not args.ir:
        raise SystemExit("--cores requires --ir")
    ir = json.loads(Path(args.ir).read_text(encoding="utf-8"))
    heads = _addr_file(args.boundary_heads)
    disp = _addr_file(args.dispatch_entries)
    cores: dict[str, str] = {}
    refused: dict[str, str] = {}
    for key in wanted:
        prop = census["functions"][key]
        if prop["refusals"]:
            refused[key] = "contract-not-promotable"
            continue
        scan, why = scan_for(ir["functions"][key])
        if scan is None:
            refused[key] = why
            continue
        cs = int(key.split(":")[0], 16)
        name = None
        for n in prop.get("notes", ()):
            if n.startswith("name: "):
                name = n.split()[1]
        try:
            cores[key] = emit_abi.emit_abi_core(
                scan, prop, key, name=name,
                boundary_addrs={ip for (hc, ip) in heads if hc == cs},
                dispatch_addrs={ip for (hc, ip) in disp if hc == cs})
        except Refusal as e:
            refused[key] = str(e)

    print(f"de-stacked ABI core emission over {len(wanted)} candidates:")
    print(f"  cores emitted  {len(cores):4d}")
    from collections import Counter
    print("  kept mechanical (slice-3 work list):")
    for reason, n in Counter(refused.values()).most_common():
        print(f"    {reason:<44} {n:4d}")
    if args.apply and cores:
        out = Path(args.out_dir)
        out.mkdir(parents=True, exist_ok=True)
        for key, src in sorted(cores.items()):
            (out / f"core_{emit_abi._stem(key)}.py").write_text(
                src, encoding="utf-8")
        manifest = {"_notice": "GENERATED by dos_re tools/abi_promote.py "
                               "--cores. Regenerate, do not hand-edit.",
                    "cores": sorted(cores)}
        (out / "cores_manifest.json").write_text(
            json.dumps(manifest, indent=1), encoding="utf-8")
        print(f"wrote {len(cores)} core modules + cores_manifest.json "
              f"to {out}")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--census", required=True,
                    help="contract_census.json (dos_re.lift.contracts)")
    ap.add_argument("--import-base", required=True,
                    help="package of the mechanical recovered modules")
    ap.add_argument("--abi-base", required=True,
                    help="package the ABI modules are imported as")
    ap.add_argument("--out-dir", required=True)
    ap.add_argument("--all", action="store_true",
                    help="emit every promotable contract (default: only "
                         "those with dropped outputs -- the poison-proof "
                         "set)")
    ap.add_argument("--cores", action="store_true",
                    help="slice 2: emit DE-STACKED ABI cores "
                         "(core_CCCC_IIII.py) for every destackable leaf; "
                         "requires --ir; prints the destack refusal census "
                         "(the slice-3 work list)")
    ap.add_argument("--ir", default=None,
                    help="recovery_ir.json (required for --cores)")
    ap.add_argument("--boundary-heads", default=None,
                    help="@FILE of boundary-head CS:IP addresses (a park-"
                         "carrying function stays mechanical)")
    ap.add_argument("--dispatch-entries", default=None,
                    help="@FILE of dynamic-arrival CS:IP addresses (an "
                         "alt-entry function stays mechanical)")
    ap.add_argument("--entries", default="",
                    help="comma-separated CS:IP subset (bisection aid)")
    ap.add_argument("--apply", action="store_true",
                    help="write the generated files (default: dry run)")
    args = ap.parse_args(argv)

    census = json.loads(Path(args.census).read_text(encoding="utf-8"))
    wanted = ([e.strip().upper() for e in args.entries.split(",")
               if e.strip()] or sorted(census["functions"]))

    if args.cores:
        return _emit_cores(args, census, wanted)

    emitted: dict[str, str] = {}
    skipped: dict[str, str] = {}
    for key in wanted:
        prop = census["functions"][key]
        if prop["refusals"]:
            skipped[key] = "refused: " + ",".join(
                r["reason"] for r in prop["refusals"])
            continue
        if not args.all and not prop["dropped_outputs"]:
            skipped[key] = "no-dropped-outputs"
            continue
        name = None
        for n in prop.get("notes", ()):
            if n.startswith("name: "):
                name = n.split()[1]
        try:
            emitted[key] = emit_abi.emit_abi_module(
                key, prop, import_base=args.import_base, name=name)
        except Refusal as e:
            skipped[key] = str(e)

    print(f"ABI-recovered emission over {len(wanted)} candidates:")
    print(f"  emitted  {len(emitted):4d}")
    from collections import Counter
    for reason, n in Counter(skipped.values()).most_common():
        print(f"  skipped: {reason:<40} {n:4d}")

    if args.apply and emitted:
        out = Path(args.out_dir)
        out.mkdir(parents=True, exist_ok=True)
        for key, src in sorted(emitted.items()):
            (out / f"abi_{emit_abi._stem(key)}.py").write_text(
                src, encoding="utf-8")
        (out / "shadow_loader.py").write_text(
            emit_abi.emit_shadow_loader(sorted(emitted),
                                        abi_base=args.abi_base,
                                        import_base=args.import_base),
            encoding="utf-8")
        (out / "__init__.py").write_text(
            '"""AUTOGENERATED by dos_re tools/abi_promote.py -- '
            'ABI-recovered contract modules (M3b slice 1).  Regenerate, '
            'do not hand-edit."""\n', encoding="utf-8")
        print(f"wrote {len(emitted)} modules + shadow_loader to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
