#!/usr/bin/env python3
"""codemap — derive function-entry evidence from observed execution.

A game-side probe may drive any relevant scenario under a step wrapper and
dump an ``observed.json``:

    {
      "executed":            ["CS:IP", ...],   # every stepped instruction start
      "call_targets":        {"CS:IP": count}, # dynamically observed CALL targets
      "int_entries":         ["CS:IP", ...],   # ISR entries vectored by INT n
      "ivt_game_vectors":    {"NN": "CS:IP"},  # final IVT vectors into game code
      ...
    }

This tool projects those observations into an entry list that static analysis
or generation commands may consume:

    entries = (call_targets that were actually entered)
            | int_entries | ivt_game_vectors | --extra entries

Dynamic evidence complements static analysis: an indirect call's observed
targets appear in ``call_targets`` even when a static analysis cannot resolve
them. Every kept entry was executed in the contributing observations.

Usage:
    python tools/codemap.py --observed artifacts/codemap/observed.json \
        --out entries.txt [--seg 1010] [--min-calls 1] [--extra CS:IP ...]
    python tools/liftgen.py --exe GAME.EXE --snapshot SNAP --entries-file entries.txt
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def parse_addr(text: str) -> tuple[int, int]:
    cs, ip = text.split(":", 1)
    return int(cs, 16) & 0xFFFF, int(ip, 16) & 0xFFFF


def derive_entries(observed: dict, *, segments: set[int] | None = None,
                   min_calls: int = 1,
                   extra: tuple[tuple[int, int], ...] = ()) -> list[tuple[int, int]]:
    """Entry set from an observed-execution dump (pure; unit-tested).

    A call target counts only if it was actually executed (a target address
    that never ran was a mis-observed transfer, not a function).  INT-vectored
    ISR entries and installed IVT vectors are entries regardless of call
    counts — they are entered by hardware/INT dispatch, not CALL.
    """
    executed = {parse_addr(a) for a in observed.get("executed", ())}
    entries: set[tuple[int, int]] = set()
    for addr_text, count in observed.get("call_targets", {}).items():
        addr = parse_addr(addr_text)
        if count >= min_calls and addr in executed:
            entries.add(addr)
    for addr_text in observed.get("int_entries", ()):
        addr = parse_addr(addr_text)
        if addr in executed:
            entries.add(addr)
    for addr_text in observed.get("ivt_game_vectors", {}).values():
        addr = parse_addr(addr_text)
        if addr in executed:
            entries.add(addr)
    entries.update(extra)
    if segments is not None:
        entries = {a for a in entries if a[0] in segments}
    return sorted(entries)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--observed", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--seg", action="append", default=[],
                    help="restrict entries to these code segments (hex, repeatable)")
    ap.add_argument("--min-calls", type=int, default=1)
    ap.add_argument("--extra", action="append", default=[], metavar="CS:IP",
                    help="extra known entries (e.g. the boot entry point)")
    args = ap.parse_args(argv)

    observed = json.loads(Path(args.observed).read_text())
    segments = {int(s, 16) & 0xFFFF for s in args.seg} or None
    extra = tuple(parse_addr(a) for a in args.extra)
    entries = derive_entries(observed, segments=segments,
                             min_calls=args.min_calls, extra=extra)

    lines = ["# generated by tools/codemap.py from %s" % args.observed]
    lines += ["%04X:%04X" % a for a in entries]
    Path(args.out).write_text("\n".join(lines) + "\n")
    print("wrote %s: %d entries (executed=%d, observed call targets=%d)"
          % (args.out, len(entries), len(observed.get("executed", ())),
             len(observed.get("call_targets", {}))))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
