"""ea_census.py -- read-only effective-address evidence.

docs/memory_schema.md §14.2.  Emits symbolic address expressions, candidate
regions, segment aliases and structured blockers over the recovery IR.  It
rewrites nothing: §6 selects the first promotion region FROM this evidence
rather than prescribing one, after a prescribed region turned out to have a
~56-function ownership closure hidden behind a segment alias.

Usage:
    python dos_re/tools/ea_census.py --ir artifacts/lift/recovery_ir.json \
        [--out artifacts/analysis/ea_census.json] [--top 20]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from dos_re.lift import ea_census  # noqa: E402
from dos_re.lift.contracts import scan_for  # noqa: E402


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--ir", required=True)
    ap.add_argument("--out", default=None)
    ap.add_argument("--top", type=int, default=15,
                    help="how many candidate regions to list per section")
    args = ap.parse_args(argv)

    ir = json.loads(Path(args.ir).read_text(encoding="utf-8"))
    c = ea_census.build(ir, scan_for)

    static = c.static_clusters()
    indexed = c.indexed_clusters()
    aliases = c.segment_aliases()

    print(f"EA census over {len(ir.get('functions', {}))} functions:")
    print(f"  memory sites          {len(c.sites):5d}")
    print(f"    static (fixed base) {sum(1 for s in c.sites if s.is_static):5d}"
          f"   -> {len(static)} distinct (segment, offset)")
    print(f"    register-indexed    "
          f"{sum(1 for s in c.sites if not s.is_static):5d}"
          f"   -> {len(indexed)} distinct (segment, base, index)")
    print(f"  blockers              {len(c.blockers):5d}")
    if c.blockers:
        from collections import Counter
        for reason, n in Counter(b.reason.split(":")[0]
                                 for b in c.blockers).most_common(6):
            print(f"    {reason:<34} {n:5d}")

    # SEGMENT ALIASES FIRST: they decide whether a region's byte extent is an
    # honest measure of its cost.  A tiny range reached through two segments
    # has an ownership closure spanning every function using either spelling.
    print(f"\nSEGMENT ALIASES ({len(aliases)} offsets reached via >1 segment)"
          " -- these are NOT small slices:")
    for disp in sorted(aliases, key=lambda d: -len(c.closure(d)))[:args.top]:
        segs = ", ".join(f"{s}={n}" for s, n in sorted(aliases[disp].items()))
        print(f"  {disp:#06x}: {segs:<28} closure={len(c.closure(disp))} funcs")

    # candidate first regions: smallest ownership closure, alias-free
    print(f"\nSMALLEST ALIAS-FREE STATIC CANDIDATES (closure = functions that"
          f" must be owned together):")
    cands = [((seg, disp), sites) for (seg, disp), sites in static.items()
             if disp not in aliases]
    for (seg, disp), sites in sorted(cands,
                                     key=lambda kv: len(c.closure(kv[0][1])))[:args.top]:
        w = sorted({s.width for s in sites})
        wr = sum(1 for s in sites if s.writes)
        print(f"  {seg}:[{disp:#06x}]  closure={len(c.closure(disp)):3d} funcs"
              f"  sites={len(sites):3d} (writes {wr})  width={w}")

    print(f"\nLARGEST INDEXED CLUSTERS (array/struct candidates; displacements"
          f" are field-offset evidence):")
    for (seg, base, index), sites in sorted(
            indexed.items(), key=lambda kv: -len(kv[1]))[:args.top]:
        disps = sorted({s.disp for s in sites})
        shown = ", ".join(f"{d:+#x}" for d in disps[:8])
        print(f"  {seg}:[{base}{'+' + index if index else ''}]  "
              f"sites={len(sites):4d}  {len(disps)} offsets: {shown}"
              + (" ..." if len(disps) > 8 else ""))

    if args.out:
        Path(args.out).parent.mkdir(parents=True, exist_ok=True)
        Path(args.out).write_text(json.dumps({
            "_notice": "GENERATED by dos_re tools/ea_census.py -- READ-ONLY "
                       "address-expression census. Region selection "
                       "consumes this; nothing here promotes anything.",
            "sites": [{"key": s.key, "ip": s.ip, "segment": s.segment,
                       "base": s.base, "index": s.index, "disp": s.disp,
                       "width": s.width, "writes": s.writes}
                      for s in c.sites],
            "blockers": [{"key": b.key, "ip": b.ip, "reason": b.reason}
                         for b in c.blockers],
            "segment_aliases": {f"{d:#06x}": segs
                                for d, segs in sorted(aliases.items())},
        }, indent=1) + "\n", encoding="utf-8")
        print(f"\nwrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
