#!/usr/bin/env python3
"""irgen — generate Recovery IR (docs/recovery_ir.md) from canonical inputs.

Original binary + code-byte snapshot + entries + explicit recovery facts
produce one deterministic ``recovery_ir.json``.  This is one optional static
evidence producer; replay and manual evidence may enrich the same program
model independently.  The tool is the DOS front-end over the generic core
(``dos_re.lift.irgen_core``): it supplies the DOS triple — an MZ-snapshot
fetch, a cloned-interpreter probe, and the INT/port effect tagger — while the
core owns the per-entry scan, record serialization, unsupported ledger, and
deterministic JSON write.  Nothing here invents a second decoder.  Downstream,
emitters and analyses may consume the IR, and the whole document remains
disposable and reproducible from its declared inputs.

Usage:
    python tools/irgen.py --exe GAME.EXE --snapshot DIR \
        --entries-file entries.txt [--environment-waits @FILE] \
        [--out recovery_ir.json]
"""
from __future__ import annotations

import argparse
import hashlib
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from dos_re.lift.irgen_core import (  # noqa: E402
    IR_VERSION, build_document, dos_effect_tag, write_document)
from dos_re.snapshot import load_snapshot, parse_addr  # noqa: E402

_NOTICE = ("AUTOGENERATED by dos_re tools/irgen.py -- DO NOT HAND EDIT. "
           "Regenerate from the original binary, snapshot, entries, "
           "recovery facts, and the current DOS_RE toolchain "
           "(docs/recovery_ir.md).")

def _probe(rt, cs):
    """Interpreter IP-delta probe (shared impl: it RESTORES the code segment after each step, since
    a probe step runs with meaningless registers and can otherwise overwrite the bytes a later probe
    decodes -- see dos_re.lift.probe)."""
    from dos_re.lift.probe import make_ip_delta_probe
    return make_ip_delta_probe(rt, cs)


def _fetch_for_mem(mem, cs):
    return lambda off: mem.rb(cs, off & 0xFFFF)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--exe", required=True)
    ap.add_argument("--snapshot", required=True)
    ap.add_argument("--game-root", default=None)
    ap.add_argument("--entries-file", required=True)
    ap.add_argument("--environment-waits", default=None, metavar="@FILE",
                    help="entries with an evidence-backed environment-wait "
                         "effect (one CS:IP per line); tagged env_wait in IR")
    ap.add_argument("--boundary-heads", default=None, metavar="@FILE",
                    help="boundary/wait head addresses (one CS:IP per line) "
                         "-- marked as BoundaryEffect sites in the IR; the "
                         "emitter generates host-side events + ResumePoints "
                         "from them")
    ap.add_argument("--dispatch-entries", default=None, metavar="@FILE",
                    help="dynamic dispatch-entry addresses (one CS:IP per "
                         "line) -- marked DynamicDispatchEntry in the IR; "
                         "re-entry points into the containing function")
    ap.add_argument("--out", default="recovery_ir.json")
    args = ap.parse_args(argv)

    entries = []
    for line in Path(args.entries_file).read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            entries.append(parse_addr(line))

    environment_waits: set[str] = set()
    if args.environment_waits:
        path = args.environment_waits.lstrip("@")
        for line in Path(path).read_text().splitlines():
            line = line.split("#", 1)[0].strip()
            if line:
                environment_waits.add(line.upper())

    def _read_pairs(argval):
        if not argval:
            return frozenset()
        out = []
        for line in Path(argval.lstrip("@")).read_text().splitlines():
            line = line.split("#", 1)[0].strip()
            if line:
                out.append(parse_addr(line))
        return frozenset(out)
    heads = _read_pairs(args.boundary_heads)
    dispatch = _read_pairs(args.dispatch_entries)

    rt = load_snapshot(args.exe, args.snapshot, game_root=args.game_root)
    rt.cpu.trace_enabled = False
    mem = rt.cpu.mem

    try:
        toolchain = subprocess.run(
            ["git", "-C", str(ROOT), "rev-parse", "HEAD"],
            capture_output=True, text=True, check=True).stdout.strip()
    except Exception:  # noqa: BLE001
        toolchain = "unknown"

    doc = build_document(
        entries,
        fetch_for=lambda cs: _fetch_for_mem(mem, cs),
        probe_for=lambda cs: _probe(rt, cs),
        effect_tagger=dos_effect_tag,
        provenance={
            "exe": f"{Path(args.exe).name} sha1="
                   f"{hashlib.sha1(Path(args.exe).read_bytes()).hexdigest()}",
            # Recovery IR is retained project evidence. Machine-specific
            # absolute paths would make identical inputs serialize differently.
            "snapshot": Path(args.snapshot).name,
            "toolchain": toolchain,
            "entries": len(entries),
        },
        notice=_NOTICE,
        environment_wait_entries=environment_waits,
        boundary_heads=heads,
        dispatch_entries=dispatch,
    )
    out = write_document(doc, args.out)
    functions, unsupported = doc["functions"], doc["unsupported"]
    n_liftable = sum(1 for f in functions.values() if f["liftable"])
    print(f"recovery IR v{IR_VERSION}: {len(functions)} functions "
          f"({n_liftable} liftable, {len(unsupported)} unsupported records) "
          f"-> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
