#!/usr/bin/env python3
"""irgen — generate the recovery IR (docs/recovery_ir.md) from canonical inputs.

The serialization step of the DOS_RE 2.0 pipeline: original binary + code-byte
snapshot + entries + explicit recovery facts → one deterministic
``recovery_ir.json``.  This tool is the DOS front-end over the generic core
(``dos_re.lift.irgen_core``): it supplies the DOS triple — an MZ-snapshot
fetch, a cloned-interpreter probe, and the INT/port effect tagger — while the
core owns the per-entry scan, record serialization, unsupported ledger, and
deterministic JSON write.  Nothing here invents a second decoder.  Downstream,
every emitter consumes the IR (the VMless emitter via ``liftemit --from-ir``),
analyses annotate it, and the whole document is disposable/regeneratable.

Usage:
    python tools/irgen.py --exe GAME.EXE --snapshot DIR \
        --entries-file entries.txt [--keep-interpreted @FILE] \
        [--out recovery_ir.json]
"""
from __future__ import annotations

import argparse
import hashlib
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from dos_re.lift.irgen_core import (  # noqa: E402
    IR_VERSION, _INT_TAGS, _PORT_TAGS, build_document, dos_effect_tag,
    function_record, signature_for, write_document)
from dos_re.lift.cfg import FunctionScan  # noqa: E402,F401 (re-export)
from dos_re.snapshot import load_snapshot, parse_addr  # noqa: E402

_NOTICE = ("AUTOGENERATED by dos_re tools/irgen.py -- DO NOT HAND EDIT. "
           "Regenerate from the original binary, snapshot, entries, "
           "recovery facts, and the current DOS_RE toolchain "
           "(docs/recovery_ir.md).")

#: back-compat alias — the recognizer now lives in dos_re.lift.irgen_core.
_effect_tag = dos_effect_tag


def _probe(rt, cs):
    from dos_re.repro_artifacts import clone_runtime_state
    scratch = clone_runtime_state(rt)
    cpu = scratch.cpu
    cpu.replacement_hooks.clear(); cpu.hook_names.clear()
    cpu.hook_verifier = None; cpu.trace_enabled = False; cpu.pending_irq = None

    def probe(ip):
        ip &= 0xFFFF
        cpu.s.cs, cpu.s.ip = cs & 0xFFFF, ip
        try:
            cpu.step()
        except Exception:  # noqa: BLE001
            return None
        return ((cpu.s.ip - ip) & 0xFFFF) or None
    return probe


def _fetch_for_mem(mem, cs):
    return lambda off: mem.rb(cs, off & 0xFFFF)


def _signature(mem, cs: int, ip: int, scan: FunctionScan) -> bytes:
    """Back-compat shim over ``irgen_core.signature_for`` (mem-based recipe)."""
    return signature_for(_fetch_for_mem(mem, cs), ip, scan)


def _function_record(scan: FunctionScan, cs: int, ip: int, mem,
                     keep_interpreted: set[str],
                     boundary_heads: frozenset = frozenset(),
                     dispatch_entries: frozenset = frozenset()) -> dict:
    """Back-compat shim over ``irgen_core.function_record`` (mem-based)."""
    return function_record(scan, cs, ip, _fetch_for_mem(mem, cs),
                           keep_interpreted, boundary_heads=boundary_heads,
                           dispatch_entries=dispatch_entries,
                           effect_tagger=dos_effect_tag)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--exe", required=True)
    ap.add_argument("--snapshot", required=True)
    ap.add_argument("--game-root", default=None)
    ap.add_argument("--entries-file", required=True)
    ap.add_argument("--keep-interpreted", default=None, metavar="@FILE",
                    help="the port's keep-interpreted list (one CS:IP per "
                         "line) -- tagged env_wait in the IR")
    ap.add_argument("--boundary-heads", default=None, metavar="@FILE",
                    help="boundary/wait head addresses (one CS:IP per line) "
                         "-- marked as BoundaryEffect sites in the IR; the "
                         "emitter generates host-side events + ResumePoints "
                         "from them")
    ap.add_argument("--dispatch-entries", default=None, metavar="@FILE",
                    help="dynamic dispatch-entry addresses (one CS:IP per "
                         "line) -- marked DynamicDispatchEntry in the IR; "
                         "re-entry points into the containing function")
    ap.add_argument("--out", default="recovery_ir.json")
    args = ap.parse_args(argv)

    entries = []
    for line in Path(args.entries_file).read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            entries.append(parse_addr(line))

    keep: set[str] = set()
    if args.keep_interpreted:
        path = args.keep_interpreted.lstrip("@")
        for line in Path(path).read_text().splitlines():
            line = line.split("#", 1)[0].strip()
            if line:
                keep.add(line.upper())

    def _read_pairs(argval):
        if not argval:
            return frozenset()
        out = []
        for line in Path(argval.lstrip("@")).read_text().splitlines():
            line = line.split("#", 1)[0].strip()
            if line:
                out.append(parse_addr(line))
        return frozenset(out)
    heads = _read_pairs(args.boundary_heads)
    dispatch = _read_pairs(args.dispatch_entries)

    rt = load_snapshot(args.exe, args.snapshot, game_root=args.game_root)
    rt.cpu.trace_enabled = False
    mem = rt.cpu.mem

    try:
        toolchain = subprocess.run(
            ["git", "-C", str(ROOT), "rev-parse", "HEAD"],
            capture_output=True, text=True, check=True).stdout.strip()
    except Exception:  # noqa: BLE001
        toolchain = "unknown"

    doc = build_document(
        entries,
        fetch_for=lambda cs: _fetch_for_mem(mem, cs),
        probe_for=lambda cs: _probe(rt, cs),
        effect_tagger=dos_effect_tag,
        provenance={
            "exe": f"{Path(args.exe).name} sha1="
                   f"{hashlib.sha1(Path(args.exe).read_bytes()).hexdigest()}",
            "snapshot": str(args.snapshot),
            "toolchain": toolchain,
            "entries": len(entries),
        },
        notice=_NOTICE,
        keep_interpreted=keep,
        boundary_heads=heads,
        dispatch_entries=dispatch,
    )
    out = write_document(doc, args.out)
    functions, unsupported = doc["functions"], doc["unsupported"]
    n_liftable = sum(1 for f in functions.values() if f["liftable"])
    print(f"recovery IR v{IR_VERSION}: {len(functions)} functions "
          f"({n_liftable} liftable, {len(unsupported)} unsupported records) "
          f"-> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
