"""Scaffold a dos_re 3.0 game recovery project.

The replacement for the retired DOS_RE 1.0 starter repository
(template_dos_port): instead of cloning a big template that drifts, this
generates a MINIMAL skeleton that consumes the checked-out ``dos_re``
framework (docs/getting_started.md).  The skeleton establishes:

    project configuration + .gitignore (originals never committed)
    assets/ as recovery-time input only
    <game>/recovery_facts/ (evidence-backed facts the pipeline consumes)
    <game>/lifted/ for the generated corpus (AUTOGENERATED banner)
    artifacts/ (demos) + generated/ (boot image), both git-ignored
    scripts/play.py (the one profile-driven development/release entrypoint)
    tests/ with the layer-dependency and ASCII-output guardrails

Usage:
    python dos_re/tools/new_project.py --game mygame --output ../mygame_port \
        [--exe MYGAME.EXE]

After generating: add dos_re as a git submodule at <output>/dos_re, put your
original game files in assets/, and follow docs/getting_started.md.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path


def _w(root: Path, rel: str, text: str) -> None:
    p = root / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    if p.exists():
        raise SystemExit(f"refusing to overwrite existing file: {p}")
    p.write_text(text, encoding="utf-8", newline="\n")
    print(f"  {rel}")


def scaffold(game: str, out: Path, exe_name: str) -> None:
    g = game.lower()
    if not g.isidentifier():
        raise SystemExit(f"--game must be a valid Python identifier: {game!r}")
    out.mkdir(parents=True, exist_ok=True)
    print(f"scaffolding dos_re 3.0 port {g!r} in {out}")

    _w(out, "README.md", f"""# {g}_port -- a dos_re 3.0 recovery project

Started with `dos_re/tools/new_project.py`.

- Execution architecture: `dos_re/docs/execution_planner.md`
- Override architecture: `dos_re/docs/override_architecture.md`
- Workflow: `dos_re/docs/getting_started.md`

Bring your own original game files into `assets/` (git-ignored; the binary is
development-time input only. A release plan and export must not load it.
""")

    _w(out, ".gitignore", """# Original game files never belong in this repo (bring your own)
assets/

# Demos/snapshots carry original-game memory: local only
artifacts/

# Generated data-only boot image: derived from the original binary, local only
generated/

__pycache__/
*.pyc
""")

    _w(out, "AGENTS.md", f"""# AGENTS.md -- operating card ({g}, dos_re 3.0)

Authority: `dos_re/docs/execution_planner.md`,
`dos_re/docs/override_architecture.md`, then
`dos_re/docs/getting_started.md`. Deterministic tooling transforms the corpus;
record evidence-backed recovery facts in `{g}/recovery_facts/` and never
hand-edit generated output. `scripts/play.py` is the only player. Recovery
levels belong to implementation catalog entries, not runner names.
""")

    _w(out, f"{g}/__init__.py", "")
    _w(out, f"{g}/runtime.py", f'''"""{g} adapter runtime wiring (the game-specific boot knowledge).

Everything here is game knowledge: the EXE identity, boot-time inputs, and
game-specific interrupt quirks that must NOT live in the game-agnostic
framework (dos_re).  This module is the ONLY place that loads the original
executable -- and only for development/oracle paths, never for a detached plan.
"""
from __future__ import annotations

from pathlib import Path

from dos_re.runtime import Runtime, create_runtime

EXE_NAME = "{exe_name}"


def create_{g}_runtime(exe_path: str | Path, *, game_root: str | Path | None = None,
                       command_tail: bytes | str = b"") -> Runtime:
    """Boot the interpreted oracle for the original executable.

    Add boot-time input feeding / interrupt quirks here as you discover them
    (see lemmings_port/lemmings/runtime.py for a worked example)."""
    return create_runtime(exe_path, game_root=game_root, command_tail=command_tail)
''')

    _w(out, f"{g}/facts.py", f'''"""Loader for {g}'s structured recovery facts (recovery_facts/recovery_facts.json).

The 2.0 rule (dos_re/docs/dos_re_2.0.md section 3): game-specific knowledge
lives in explicit, evidence-backed, versioned declarations that the PIPELINE
consumes -- never in hand-edits to generated output.
"""
from __future__ import annotations

import json
from pathlib import Path

_FACTS_PATH = (Path(__file__).resolve().parent / "recovery_facts"
               / "recovery_facts.json")


def load_facts() -> dict:
    return json.loads(_FACTS_PATH.read_text(encoding="utf-8"))


def keep_interpreted_entries() -> set[str]:
    """The automation-gap queue ("CS:IP" strings).

    Every reachable entry must be covered before a detached plan is valid.
    """
    return {{rec["entry"].upper() for rec in load_facts().get("keep_interpreted", ())}}


def code_as_data_ranges() -> list[tuple[int, int]]:
    """Declared code_as_data ranges as (linear_start, length) -- recovered code
    bytes the game READS AS DATA; the boot-image poison must preserve them."""
    out = []
    for rec in load_facts().get("code_as_data", ()):
        lin = rec["linear"]
        start = int(lin, 16) if isinstance(lin, str) else int(lin)
        out.append((start, int(rec["length"])))
    return out
''')

    _w(out, f"{g}/recovery_facts/recovery_facts.json", """{
 "$schema_note": "Structured, evidence-backed, game-specific recovery facts (dos_re/docs/dos_re_2.0.md section 3). The pipeline consumes these; generated output never encodes them by hand-edit. Every fact carries provenance (why + evidence + recorded date).",
 "game": "GAME_NAME",
 "keep_interpreted": [],
 "code_as_data": [],
 "notes": []
}
""".replace("GAME_NAME", g))

    _w(out, f"{g}/lifted/README.md", f"""# `{g}/lifted/` -- the VMless machine-shaped projection (generated)

**AUTOGENERATED -- DO NOT HAND EDIT.**  Populated by the dos_re pipeline:

```
irgen (binary+snapshot+entries+facts) -> recovery_ir.json
  -> liftemit --from-ir   -> liftlink --from-ir
```

See dos_re/docs/dos_re_2.0.md section 1 for the generated-code contract.
""")

    _w(out, "scripts/play.py", f'''"""The single {g} execution entrypoint.

Recovery levels are implementation properties. Select development,
verification, detached, or release policy with ``--profile``.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "dos_re"))

from dos_re import player  # noqa: E402

from {g}.runtime import create_{g}_runtime, EXE_NAME  # noqa: E402


class GameFrontend(player.GameFrontend):
    name = "{g}"
    default_exe = str(ROOT / "assets" / EXE_NAME)
    default_game_root = str(ROOT / "assets")

    def create_runtime(self, args):
        return create_{g}_runtime(args.exe, game_root=args.game_root,
                                  command_tail=args.dos_args)


def main(argv=None) -> int:
    return player.main(GameFrontend(ROOT), argv, description=__doc__)


if __name__ == "__main__":
    raise SystemExit(main())
''')

    _w(out, "tests/test_layer_dependencies.py", f'''"""Static architectural guardrails (dos_re/docs/dos_re_2.0.md section 1a).

The stage a directory claims must be enforced by what it may IMPORT: these
rules hold even while higher stages are empty stubs.
"""
from __future__ import annotations

import ast
from pathlib import Path

PKG = Path(__file__).resolve().parents[1] / "{g}"


def _imports(path):
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    names = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            names.update(a.name for a in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module and node.level == 0:
            names.add(node.module)
    return names


def test_recovered_and_model_are_cpuless():
    for pkg in ("recovered", "model"):
        d = PKG / pkg
        if not d.is_dir():
            continue
        offenders = [f"{{p.name}} imports {{imp}}"
                     for p in d.rglob("*.py")
                     for imp in _imports(p) if imp.split(".")[0] == "dos_re"]
        assert not offenders, offenders
''')

    print("\nnext steps:")
    print(f"  1. cd {out} && git init && git submodule add <dos_re repo url> dos_re")
    print(f"  2. put your original game files into assets/ (incl. {exe_name})")
    print("  3. follow dos_re/docs/getting_started.md (make scripts/play.py boot)")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--game", required=True,
                    help="short package name for the port (python identifier)")
    ap.add_argument("--output", required=True, help="directory to create")
    ap.add_argument("--exe", default=None,
                    help="original executable filename (default GAME.EXE)")
    args = ap.parse_args(argv)
    exe = args.exe or f"{args.game.upper()}.EXE"
    scaffold(args.game, Path(args.output), exe)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
